SELECT EMPLOYEE_ID as Funcionario_ID, SALARY as Salario, DEPARTMENT_NAME as Departamento, CITY as Cidade, STATE_PROVINCE as Estado, COUNTRY_NAME as Pais, REGION_NAME as Regiao 
FROM HR.EMPLOYEES
left join HR.DEPARTMENTS
on HR.EMPLOYEES.DEPARTMENT_ID = HR.DEPARTMENTS.DEPARTMENT_ID
left join HR.LOCATIONS
on HR.LOCATIONS.LOCATION_ID = HR.DEPARTMENTS.LOCATION_ID
left join HR.COUNTRIES
on HR.COUNTRIES.COUNTRY_ID = HR.LOCATIONS.COUNTRY_ID
left join HR.REGIONS
on HR.REGIONS.REGION_ID = HR.COUNTRIES.REGION_ID
where REGION_NAME is NOT NULL