SELECT EMPLOYEE_ID as Funcionario_ID, SALARY as Salario, DEPARTMENT_NAME as Departamento, JOB_TITLE as Cargo FROM HR.EMPLOYEES
left join HR.DEPARTMENTS
on HR.EMPLOYEES.DEPARTMENT_ID = HR.DEPARTMENTS.DEPARTMENT_ID
left join HR.JOBS
on HR.EMPLOYEES.JOB_ID = HR.JOBS.JOB_ID
where DEPARTMENT_NAME is NOT NULL